export default [
    {
      id: 1,
      trajet: "Yaoundé - Bafia",
      datecreation: "2023-01-06",
      statut: "Private",
    },
    {
      id: 2,
      trajet: "Dschang - Douala",
      datecreation: "2023-01-06",
      statut: "Completed",
    },
    {
      id: 3,
      trajet: "Yaoundé - Bafia",
      datecreation: "2023-01-06",
      statut: "Published",
    },
    {
      id: 4,
      trajet: "Bafoussam - Yaoundé",
      datecreation: "2023-01-06",
      statut: "Published",
    },
    {
      id: 5,
      trajet: "Yaoundé - Douala",
      datecreation: "2023-01-06",
      statut: "Published",
    },
    {
      id: 6,
      trajet: "Yaoundé - Bafia",
      datecreation: "2023-01-06",
      statut: "Private",
    },
    {
      id: 7,
      trajet: "Dschang - Douala",
      datecreation: "2023-01-06",
      statut: "Completed",
    },
    {
      id: 8,
      trajet: "Yaoundé - Bafia",
      datecreation: "2023-01-06",
      statut: "Published",
    },
    {
      id: 9,
      trajet: "Bafoussam - Yaoundé",
      datecreation: "2023-01-06",
      statut: "Published",
    },
    {
      id: 10,
      trajet: "Yaoundé - Douala",
      datecreation: "2023-01-06",
      statut: "Completed",
    },
    {
      id: 11,
      trajet: "Yaoundé - Bafia",
      datecreation: "2023-01-06",
      statut: "Published",
    },
    {
      id: 12,
      trajet: "Bafoussam - Yaoundé",
      datecreation: "2023-01-06",
      statut: "Completed",
    },
    {
      id: 13,
      trajet: "Yaoundé - Douala",
      datecreation: "2023-01-06",
      statut: "Published",
    },
    {
      id: 14,
      trajet: "Yaoundé - Douala",
      datecreation: "2023-01-06",
      statut: "Published",
    },
    {
      id: 15,
      trajet: "Yaoundé - Bafia",
      datecreation: "2023-01-06",
      statut: "Published",
    },
    {
      id: 16,
      trajet: "Bafoussam - Yaoundé",
      datecreation: "2023-01-06",
      statut: "Completed",
    },
    {
      id: 17,
      trajet: "Yaoundé - Douala",
      datecreation: "2023-01-06",
      statut: "Published",
    },
    {
      id: 18,
      trajet: "Yaoundé - Douala",
      datecreation: "2023-01-06",
      statut: "Published",
    },
    {
      id: 19,
      trajet: "Yaoundé - Bafia",
      datecreation: "2023-01-06",
      statut: "Published",
    },
    {
      id: 20,
      trajet: "Bafoussam - Yaoundé",
      datecreation: "2023-01-06",
      statut: "Private",
    },
    {
      id: 21,
      trajet: "Yaoundé - Douala",
      datecreation: "2023-01-06",
      statut: "Published",
    },
    {
      id: 22,
      trajet: "Bafoussam - Yaoundé",
      datecreation: "2023-01-06",
      statut: "Completed",
    },
    {
      id: 23,
      trajet: "Yaoundé - Douala",
      datecreation: "2023-01-06",
      statut: "Published",
    }
  ];